/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "Assignment2.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
example_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		pwdd pwd_1_arg;
		strings echo_1_arg;
		FileExists strconc_1_arg;
		sort_request sorting_1_arg;
		matrix_input matrix_multi_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case pwd:
		_xdr_argument = (xdrproc_t) xdr_pwdd;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) pwd_1_svc;
		break;

	case ECHO:
		_xdr_argument = (xdrproc_t) xdr_strings;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) echo_1_svc;
		break;

	case STRCONC:
		_xdr_argument = (xdrproc_t) xdr_FileExists;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) strconc_1_svc;
		break;

	case SORTING:
		_xdr_argument = (xdrproc_t) xdr_sort_request;
		_xdr_result = (xdrproc_t) xdr_sort_request;
		local = (char *(*)(char *, struct svc_req *)) sorting_1_svc;
		break;

	case Matrix_Multi:
		_xdr_argument = (xdrproc_t) xdr_matrix_input;
		_xdr_result = (xdrproc_t) xdr_matrix_request;
		local = (char *(*)(char *, struct svc_req *)) matrix_multi_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (EXAMPLE_PROG, EXAMPLE_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, EXAMPLE_PROG, EXAMPLE_VERS, example_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (EXAMPLE_PROG, EXAMPLE_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, EXAMPLE_PROG, EXAMPLE_VERS, example_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (EXAMPLE_PROG, EXAMPLE_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
