/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ASSIGNMENT2_H_RPCGEN
#define _ASSIGNMENT2_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define BUFFER_SIZE 1024

struct pwdd {
	char p[BUFFER_SIZE];
};
typedef struct pwdd pwdd;

struct strings {
	char src[BUFFER_SIZE];
};
typedef struct strings strings;

struct FileExists {
	char p[BUFFER_SIZE];
};
typedef struct FileExists FileExists;

struct sort_request {
	int p;
	int arr[100];
};
typedef struct sort_request sort_request;

struct matrix_request {
	int arr[4];
};
typedef struct matrix_request matrix_request;

struct matrix_input {
	matrix_request arr1;
	matrix_request arr2;
};
typedef struct matrix_input matrix_input;

#define EXAMPLE_PROG 0x31234567
#define EXAMPLE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define pwd 1
extern  char ** pwd_1(pwdd *, CLIENT *);
extern  char ** pwd_1_svc(pwdd *, struct svc_req *);
#define ECHO 2
extern  char ** echo_1(strings *, CLIENT *);
extern  char ** echo_1_svc(strings *, struct svc_req *);
#define STRCONC 3
extern  char ** strconc_1(FileExists *, CLIENT *);
extern  char ** strconc_1_svc(FileExists *, struct svc_req *);
#define SORTING 4
extern  sort_request * sorting_1(sort_request *, CLIENT *);
extern  sort_request * sorting_1_svc(sort_request *, struct svc_req *);
#define Matrix_Multi 5
extern  matrix_request * matrix_multi_1(matrix_input *, CLIENT *);
extern  matrix_request * matrix_multi_1_svc(matrix_input *, struct svc_req *);
extern int example_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define pwd 1
extern  char ** pwd_1();
extern  char ** pwd_1_svc();
#define ECHO 2
extern  char ** echo_1();
extern  char ** echo_1_svc();
#define STRCONC 3
extern  char ** strconc_1();
extern  char ** strconc_1_svc();
#define SORTING 4
extern  sort_request * sorting_1();
extern  sort_request * sorting_1_svc();
#define Matrix_Multi 5
extern  matrix_request * matrix_multi_1();
extern  matrix_request * matrix_multi_1_svc();
extern int example_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_pwdd (XDR *, pwdd*);
extern  bool_t xdr_strings (XDR *, strings*);
extern  bool_t xdr_FileExists (XDR *, FileExists*);
extern  bool_t xdr_sort_request (XDR *, sort_request*);
extern  bool_t xdr_matrix_request (XDR *, matrix_request*);
extern  bool_t xdr_matrix_input (XDR *, matrix_input*);

#else /* K&R C */
extern bool_t xdr_pwdd ();
extern bool_t xdr_strings ();
extern bool_t xdr_FileExists ();
extern bool_t xdr_sort_request ();
extern bool_t xdr_matrix_request ();
extern bool_t xdr_matrix_input ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ASSIGNMENT2_H_RPCGEN */
